[package]
name = "tfidf"
version = "0.1.0"
edition = "2021"

[lib]
name = "tfidf"
path = "src/lib.rs"  # Ensure this points to the correct file

[dependencies]
sprs = "0.11.3"
indexmap = "2.7.1"
indicatif = "0.17.11"
rayon = "1.10.0"
ndarray = "0.16.1"
rustc-hash = "2.1.1"